import Head from "next/head";
import ContainerWrapper from "@/components/layout/ContainerWrapper";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContainerWrapper>
        <h1 className="text-3xl font-bold uppercase">Webbzy Systems</h1>
      </ContainerWrapper>
    </>
  );
}
